# Handle Data Storage

### Create a list of all Zettel

In [1]:
import pandas as pd
import regex as re

from zettelsortierung.DataTypes import *
from zettelsortierung.Transformation import *
from zettelsortierung.DataModel import DataBase

from dotenv import load_dotenv
load_dotenv()

True

### Connect to Database

In [2]:
db = DataBase()

### Add Scans

In [3]:
df = pd.read_parquet('../data/processed/Scans.parquet')
df

                                                      path
0        /home/jan/Dokumente/IT-Beratung Raring/Zettels...
1        /home/jan/Dokumente/IT-Beratung Raring/Zettels...
2        /home/jan/Dokumente/IT-Beratung Raring/Zettels...
3        /home/jan/Dokumente/IT-Beratung Raring/Zettels...
4        /home/jan/Dokumente/IT-Beratung Raring/Zettels...
...                                                    ...
2524735  /home/jan/Dokumente/IT-Beratung Raring/Zettels...
2524736  /home/jan/Dokumente/IT-Beratung Raring/Zettels...
2524737  /home/jan/Dokumente/IT-Beratung Raring/Zettels...
2524738  /home/jan/Dokumente/IT-Beratung Raring/Zettels...
2524739  /home/jan/Dokumente/IT-Beratung Raring/Zettels...

[2524740 rows x 1 columns]

In [4]:
paths_list = df['path'].to_list()
print(len(paths_list))

2524740

In [ ]:
#db.add_scan_list(paths_list)

10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000
1010000
1020000
1030000
1040000
1050000
1060000
1070000
1080000
1090000
1100000
1110000
1120000
1130000
1140000
1150000
1160000
1170000
1180000
1190000
1200000
1210000
1220000
1230000
1240000
1250000
1260000
1270000
1280000
1290000
1300000
1310000
1320000
1330000
1340000
1350000
1360000
1370000
1380000
1390000
1400000
1410000
1420000
1430000
1440000
1450000
1460000
1470000
1480000
1490000
1500000
1510000
1520000
1530000
1540000
1550000
1560000
1570000
1580000
1590000
1600000
1610000
1620000
1630000
1640000
1650000
1660000
1670000
1680000
1690000
1700000
1710000
1720000
1730000
1740000
1750000
1760000
1770000
1780000
1790000
1800000
1810000
1820000
1830000
1840000
1850000
1860000
1870000
1880000
1890000
1900000
1910000
1920000
1930000
1940000
1950000
1960000
1970000
1980000
1990000
2000000
2010000
2020000
2030000
2040000
2050000
2060000
2070000
2080000
2090000
2100000
2110000
2120000
2130000
2140000
2150000
2160000
2170000
2180000
2190000
2200000
2210000
2220000
2230000
2240000
2250000
2260000
2270000
2280000
2290000
2300000
2310000
2320000
2330000
2340000
2350000
2360000
2370000
2380000
2390000
2400000
2410000
2420000
2430000
2440000
2450000
2460000
2470000
2480000
2490000
2500000
2510000
2520000
2524740

In [2]:
res = db.get_scans()
print(len(res))
for re in res:
    print(re)
    break

2524740
ScanModel(A01-00000001_1, A01_a-Adel/1/01_a/)

In [3]:
print(res[0].to_domain())

Scan(A01-00000001_1, A01_a-Adel/1/01_a/)

### Adding Zettel

In [5]:
odd_paths = [path for path in paths_list if len(re.findall('1#', path))]
print(len(odd_paths))
print(odd_paths[0])

1262370
/home/jan/Dokumente/IT-Beratung Raring/Zettelsortierung/data/raw/zettelsammlung/A01_a-Adel/1/01_a/00000001_1#A01_1_01_a.jpg

In [6]:
zettel_list = [Zettel(path) for path in odd_paths]
print(zettel_list[0])

Zettel(A01-00000001)

In [7]:
db.add_zettel_list(zettel_list)

10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000
1010000
1020000
1030000
1040000
1050000
1060000
1070000
1080000
1090000
1100000
1110000
1120000
1130000
1140000
1150000
1160000
1170000
1180000
1190000
1200000
1210000
1220000
1230000
1240000
1250000
1260000

### Adding Landschafte

In [8]:
landschaften_df = pd.read_csv('../data/processed/Landschaften.csv', delimiter='\t')
landschaften_df

,Abkuerzung,Name,Beschreibung
0,Emsl,Emsland,"Emsland d. h. die Kreise Lingen, Meppen, Asche..."
1,HOsnabr,Hochstift Ösnabrück,"das frühere Hochstift Osnabrück, vornehmlich d..."
2,HPaderb,Hochstift Paderborn,"das frühere Hochstift Paderborn, d. h. die Kre..."
3,KSauerl,Kölnisches Sauerland,"Kölnisches Sauerland, d. h. die Kreise Arnsber..."
4,Lip,Lippe,"das frühere Land Lippe, d. h. die Kreise Detmo..."
5,Mark,Grafschaft Mark,die frühere Grafschaft Mark
6,Münsterl,Münsterland,Münsterland
7,Ravensbg,Grafschaft Ravensberg,die frühere Grafschaft Ravensberg
8,SOldbg,Südoldenburg,"Südoldenburg, d. h. die Kreise Vechta und Clop..."
9,WMünsterl,Westmünsterland,Westmünsterland

In [9]:
landschaften_list = list(landschaften_df.itertuples(index=False, name=None))
print(landschaften_list[0])

('Emsl', 'Emsland', 'Emsland d. h. die Kreise Lingen, Meppen, Aschendorf-Hümmling')

In [10]:
db.add_landschaften(landschaften_list)

### Adding Kreise

In [12]:
kreise_df = pd.read_csv('../data/processed/Kreise.csv', delimiter='\t')
kreise_df

   Abkuerzung                                               Name
0         Ahs                                          Kr. Ahaus
1         Alt          Kr. Altena u. die krfr. Stadt Lüdenscheid
2         Arn                                       Kr. Arnsberg
3         Asd                            Kr. Aschendorf-Hümmling
4         Bbr                                    Kr. Bersenbrück
5         Bch     die krfr. Städte Bochum, Herne u. Wattenscheid
6         Bek                                         Kr. Beckum
7         Ben                            Kr. Grafschaft Bentheim
8         Bie                                      Kr. Bielefeld
9         Bor              Kr. Borken u. die krfr. Stadt Bocholt
10        Brg  an Westfalen grenzende Teile der krfr. Stadt W...
11        Bri                                         Kr. Brilon
12        Bük               früherer Verwaltungsbezirk Bückeburg
13        Bür                                          Kr. Büren
14        Det                                        Kr. Detmold
15        Die                            Kr. Grafschaft Diepholz
16        Dor  die krfr. Städte Dortmund, Castrop-Rauxel u. L...
17        Enr                                  Ennepe-Ruhr-Kreis
18        Ess               die krfr. Städte Essen u. Oberhausen
19        Gel     die krfr. Städte Gelsenkirchen u. Wanne-Eickel
20        Hag                              die krfr. Stadt Hagen
21        Hal                                          Kr. Halle
22        Ham                                        Ha → Unn Hx
23        Hfd                                        Kr. Herford
24        Höx                                         Kr. Höxter
25        Isl                                       Kr. Iserlohn
26        Klo                                    Kr. Cloppenburg
27        Kos                                       Kr. Coesfeld
28        Lem                                          Kr. Lemgo
29        Lhs                                   Kr. Lüdinghausen
30        Lin                                         Kr. Lingen
31        Lst                                      Kr. Lippstadt
32        Lüb                                       Kr. Lübbecke
33        Mel                                          Kr. Melle
34        Mep                                         Kr. Meppen
35        Mes                                       Kr. Meschede
36        Min                                         Kr. Minden
37        Mün                                        Kr. Münster
38        Nie                               Kr. Nienburg (Weser)
39        Olp                                           Kr. Olpe
40        Osn                                      Kr. Osnabrück
41        Pad                                      Kr. Paderborn
42        Rek  Kr. Recklinghausen u. die krfr. Städte Bottrop...
43        Sch                          Kr. Grafschaft Schaumburg
44        Sos                                          Kr. Soest
45        Stf                                      Kr. Steinfurt
46        Sth              früherer Verwaltungsbezirk Stadthagen
47        Tek                                    Kr. Tecklenburg
48        Unn                   Kr. Unna u. die krfr. Stadt Hamm
49        Vch                                         Kr. Vechta
50        Wal  Kr. Waldeck u. Kr. Frankenberg (niederdeutsche...
51        Wbg                                        Kr. Warburg
52        Wdf                                      Kr. Warendorf
53        Wie                                    Kr. Wiedenbrück
54        Wit                             die krfr. Stadt Witten
55        Wlg                                       Kr. Wittlage
56        Wol               Kr. Wolfhagen (niederdeutscher Teil)
57        Wtg            Kr. Wittgenstein (niederdeutscher Teil)

In [13]:
kreise_list = list(kreise_df.itertuples(index=False, name=None))
print(kreise_list[0])

('Ahs', 'Kr. Ahaus')

In [14]:
db.add_kreise(kreise_list)

### Adding Orte

In [3]:
orte_df = pd.read_csv('../data/processed/Orte.csv', delimiter='\t')
orte_df

     Kreis Abkuerzung             Name
0      Ahs         Ab           Asbeck
1      Ahs         Ae      Ahle (Heek)
2      Ahs         Ah            Ahaus
3      Ahs         Al         Alstätte
4      Ahs         Am           Ammeln
...    ...        ...              ...
2727   Wol         We      Wettesingen
2728   Wol         Wh  Wenigenhasungen
2729   Wol         Wo        Wolfhagen
2730   Wtg         Lw       Langewiese
2731   Wtg         Na     Neuastenberg

[2732 rows x 3 columns]

In [4]:
orte_list = list(orte_df.itertuples(index=False, name=None))
print(orte_list[0])

('Ahs', 'Ab', 'Asbeck')

In [5]:
db.add_orte(orte_list)